version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    # Specify labels for pull requests
    labels:
      - "dependencies"
      - "security"
    # Set review requirements
    reviewers:
      - "owner"
    # Limit the number of open pull requests
    open-pull-requests-limit: 10
    # Configure security updates
    security-updates-only: false
    # Group dependencies updates
    groups:
      development-dependencies:
        patterns:
          - "@types/*"
          - "jest*"
          - "eslint*"
      production-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "@types/*"
          - "jest*"
          - "eslint*" 